// Mock product data for student products
export const MOCK_PRODUCTS = [
  {
    id: "1",
    name: "Basic Education Uniform (Elementary)",
    type: "uniform",
    category: "school_uniform",
    status: "in_stock",
    image: "/images/products/elementary-uniform.jpg",
    price: 850,
    description: "Complete school uniform set for elementary students",
  },
  {
    id: "2",
    name: "Basic Education Uniform (Senior Highschool)",
    type: "uniform",
    category: "school_uniform",
    status: "in_stock",
    image: "/images/products/senior-uniform.jpg",
    price: 950,
    description: "Complete school uniform set for senior high school students",
  },
  {
    id: "3",
    name: "Basic Education Polo (Elementary)",
    type: "uniform",
    category: "school_uniform",
    status: "in_stock",
    image: "/images/products/elementary-polo.jpg",
    price: 450,
    description: "School polo for elementary students",
  },
  {
    id: "4",
    name: "PE Uniform (Jogging Pants)",
    type: "pe_uniform",
    category: "pe_uniform",
    status: "in_stock",
    image: "/images/products/pe-pants.jpg",
    price: 550,
    description: "PE jogging pants",
  },
  {
    id: "5",
    name: "PE Uniform (Jersey)",
    type: "pe_uniform",
    category: "pe_uniform",
    status: "in_stock",
    image: "/images/products/pe-jersey.jpg",
    price: 400,
    description: "PE jersey shirt",
  },
  {
    id: "6",
    name: "Basic Education Uniform (Pre-Kindergarten)",
    type: "uniform",
    category: "school_uniform",
    status: "in_stock",
    image: "/images/products/prekinder-uniform.jpg",
    price: 750,
    description: "Complete school uniform set for pre-kindergarten students",
  },
  {
    id: "7",
    name: "Higher Education Uniform (White)",
    type: "uniform",
    category: "school_uniform",
    status: "limited_stock",
    image: "/images/products/college-white.jpg",
    price: 650,
    description: "White uniform for college students",
  },
  {
    id: "8",
    name: "PE Uniform (Full Set)",
    type: "pe_uniform",
    category: "pe_uniform",
    status: "in_stock",
    image: "/images/products/pe-fullset.jpg",
    price: 900,
    description: "Complete PE uniform set",
  },
  {
    id: "9",
    name: "Higher Education Uniform (Skirt)",
    type: "uniform",
    category: "school_uniform",
    status: "in_stock",
    image: "/images/products/college-skirt.jpg",
    price: 550,
    description: "Skirt for college students",
  },
  {
    id: "10",
    name: "School ID Lace",
    type: "other",
    category: "other_items",
    status: "in_stock",
    image: "/images/products/id-lace.jpg",
    price: 50,
    description: "Official school ID lace",
  },
  {
    id: "11",
    name: "School Bag",
    type: "other",
    category: "other_items",
    status: "pre_order",
    image: "/images/products/school-bag.jpg",
    price: 1200,
    description: "Official school bag",
  },
  {
    id: "12",
    name: "PE Shoes",
    type: "other",
    category: "other_items",
    status: "out_of_stock",
    image: "/images/products/pe-shoes.jpg",
    price: 1500,
    description: "White PE shoes",
  },
  {
    id: "13",
    name: "School Socks (White)",
    type: "other",
    category: "other_items",
    status: "in_stock",
    image: "/images/products/white-socks.jpg",
    price: 80,
    description: "White school socks",
  },
  {
    id: "14",
    name: "School Necktie",
    type: "other",
    category: "other_items",
    status: "in_stock",
    image: "/images/products/necktie.jpg",
    price: 200,
    description: "Official school necktie",
  },
  {
    id: "15",
    name: "Lab Gown",
    type: "other",
    category: "other_items",
    status: "limited_stock",
    image: "/images/products/lab-gown.jpg",
    price: 800,
    description: "Laboratory gown for science classes",
  },
  {
    id: "16",
    name: "School Jacket",
    type: "other",
    category: "other_items",
    status: "pre_order",
    image: "/images/products/jacket.jpg",
    price: 1100,
    description: "Official school jacket",
  },
];

export const PRODUCT_CATEGORIES = [
  {
    id: "all",
    label: "All Products",
    value: "all",
  },
  {
    id: "uniform",
    label: "Uniform",
    value: "uniform",
    subcategories: [
      {
        id: "school_uniform",
        label: "School Uniform",
        value: "school_uniform",
      },
      { id: "pe_uniform", label: "PE Uniform", value: "pe_uniform" },
    ],
  },
  {
    id: "other",
    label: "Other Items",
    value: "other_items",
  },
];

export const PRODUCT_STATUS = {
  in_stock: { label: "In Stock", color: "bg-green-100 text-green-800" },
  out_of_stock: { label: "Out of Stock", color: "bg-red-100 text-red-800" },
  pre_order: { label: "Pre-Order", color: "bg-blue-100 text-blue-800" },
  limited_stock: {
    label: "Limited Stocks",
    color: "bg-yellow-100 text-yellow-800",
  },
};

export const TOP_PICKS = [
  "1", // Basic Education Uniform (Elementary)
  "4", // PE Uniform (Jogging Pants)
  "7", // Higher Education Uniform (White)
  "10", // School ID Lace
];
